### ISSUE TITLE
kml 2.2 r9  external references

### ISSUE THREAD

**Issue by bermud** [opengeospatial/teamengine-offline#1]
When testing with the  latest kml reference files: 

Online - no problems

Test suite: kml22-2.2-r9
======== Test groups ========
Conformance Level 1
     Passed: 42 | Failed: 0 | Skipped: 0
Conformance Level 2
     Passed: 27 | Failed: 0 | Skipped: 0
Conformance Level 3
     Passed: 1 | Failed: 0 | Skipped: 0

Offline – had some issues with www.gdal.org and  makc.googlecode.com

Test suite: kml22-2.2-r9
      ======== Test groups ========
      Conformance Level 1
          Passed: 39 | Failed: 3 | Skipped: 0
      Conformance Level 2
          Passed: 27 | Failed: 0 | Skipped: 0
      Conformance Level 3
          Passed: 1 | Failed: 0 | Skipped: 0

```
  See detailed test report in the TE_BASE/users/CCoppock/s0004/html/ directory.
  Test method verifyLinkReferent:
                java.net.UnknownHostException: www.gdal.org
  Test method verifyModelContent:

  Severity: ERROR
  Message: Ancestor kml:Model element is missing kml:Link/kml:href value.
  Location:  pointer=xmlns(tns=http://www.opengis.net/kml/2.2)xpointer((//tns:Model)[1]) expected [false] but found [true]
  Test method verifyTextureFileAliasInModel:
                java.net.UnknownHostException: makc.googlecode.com
```

   Test tns:Main Failed
Suite tns:ets-kml22-2.2-r9 Failed

The error message generated:
C:>te-install\bin\windows\test.bat -source=c:\TE_BASE\scripts\kml22\2.2\kml22-suite.ctl
Testing suite tns:ets-kml22-2.2-r9 in Test Mode with defaultResult of Pass ...
Testing tns:Main type Mandatory in Test Mode with defaultResult Pass (s0004)...
      Assertion: The test subject satisfies all applicable constraints.
Jun 13, 2014 2:08:55 PM org.opengis.cite.kml22.util.TestSuiteLogger log
WARNING: Unable to locate Model referent.
com.sun.jersey.api.client.ClientHandlerException: java.net.UnknownHostException: makc.googlecode.com
        at com.sun.jersey.client.urlconnection.URLConnectionClientHandler.handle(URLConnectionClientHandler.java:151)
        at com.sun.jersey.api.client.Client.handle(Client.java:648)
        at com.sun.jersey.api.client.WebResource.handle(WebResource.java:680)
        at com.sun.jersey.api.client.WebResource.get(WebResource.java:191)
        at org.opengis.cite.kml22.util.URIUtils.dereferenceURI(URIUtils.java:93)
        at org.opengis.cite.kml22.level1.SpatialTests.checkModelResourceMap(SpatialTests.java:549)
        at org.opengis.cite.kml22.level1.SpatialTests.verifyModelContent(SpatialTests.java:503)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
        at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
        at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
        at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
        at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
        at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
        at org.testng.TestRunner.privateRun(TestRunner.java:767)
        at org.testng.TestRunner.run(TestRunner.java:617)
        at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
        at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
        at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
        at org.testng.SuiteRunner.run(SuiteRunner.java:240)
        at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
        at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
        at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
        at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
        at org.testng.TestNG.run(TestNG.java:1057)
        at com.occamlab.te.spi.executors.testng.TestNGExecutor.execute(TestNGExecutor.java:113)
        at org.opengis.cite.kml22.TestNGController.doTestRun(TestNGController.java:118)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at net.sf.saxon.functions.ExtensionFunctionCall.invokeMethod(ExtensionFunctionCall.java:533)
        at net.sf.saxon.functions.ExtensionFunctionCall.call(ExtensionFunctionCall.java:256)
        at net.sf.saxon.functions.ExtensionFunctionCall.iterate(ExtensionFunctionCall.java:147)
        at net.sf.saxon.instruct.CopyOf.processLeavingTail(CopyOf.java:292)
        at net.sf.saxon.instruct.Block.processLeavingTail(Block.java:409)
        at net.sf.saxon.instruct.Instruction.process(Instruction.java:94)
        at net.sf.saxon.expr.LetExpression.process(LetExpression.java:380)
        at net.sf.saxon.instruct.ForEach.processLeavingTail(ForEach.java:300)
        at net.sf.saxon.instruct.Block.processLeavingTail(Block.java:409)
        at net.sf.saxon.instruct.Template.applyLeavingTail(Template.java:175)
        at net.sf.saxon.instruct.ApplyTemplates.applyTemplates(ApplyTemplates.java:343)
        at net.sf.saxon.Controller.transformDocument(Controller.java:1736)
        at net.sf.saxon.Controller.transform(Controller.java:1560)
        at net.sf.saxon.s9api.XsltTransformer.transform(XsltTransformer.java:190)
        at com.occamlab.te.TECore.executeTemplate(TECore.java:517)
        at com.occamlab.te.TECore.executeXSLFunction(TECore.java:878)
        at com.occamlab.te.TECore.callFunction(TECore.java:910)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at net.sf.saxon.functions.ExtensionFunctionCall.invokeMethod(ExtensionFunctionCall.java:533)
        at net.sf.saxon.functions.ExtensionFunctionCall.call(ExtensionFunctionCall.java:256)
        at net.sf.saxon.functions.ExtensionFunctionCall.iterate(ExtensionFunctionCall.java:147)
        at net.sf.saxon.expr.Expression.evaluateItem(Expression.java:352)
        at net.sf.saxon.expr.Expression.process(Expression.java:461)
        at net.sf.saxon.instruct.DocumentInstr.evaluateItem(DocumentInstr.java:282)
        at net.sf.saxon.expr.ExpressionTool.evaluate(ExpressionTool.java:295)
        at net.sf.saxon.expr.LetExpression.eval(LetExpression.java:341)
        at net.sf.saxon.expr.LetExpression.processLeavingTail(LetExpression.java:542)
        at net.sf.saxon.instruct.Block.processLeavingTail(Block.java:409)
        at net.sf.saxon.expr.LetExpression.processLeavingTail(LetExpression.java:551)
        at net.sf.saxon.instruct.Block.processLeavingTail(Block.java:409)
        at net.sf.saxon.expr.LetExpression.processLeavingTail(LetExpression.java:551)
        at net.sf.saxon.instruct.Block.processLeavingTail(Block.java:409)
        at net.sf.saxon.expr.LetExpression.processLeavingTail(LetExpression.java:551)
        at net.sf.saxon.instruct.Block.processLeavingTail(Block.java:409)
        at net.sf.saxon.expr.LetExpression.processLeavingTail(LetExpression.java:551)
        at net.sf.saxon.instruct.Block.processLeavingTail(Block.java:409)
        at net.sf.saxon.instruct.Instruction.process(Instruction.java:94)
        at net.sf.saxon.expr.LetExpression.process(LetExpression.java:380)
        at net.sf.saxon.instruct.ForEach.processLeavingTail(ForEach.java:300)
        at net.sf.saxon.instruct.Template.applyLeavingTail(Template.java:175)
        at net.sf.saxon.instruct.ApplyTemplates.applyTemplates(ApplyTemplates.java:343)
        at net.sf.saxon.Controller.transformDocument(Controller.java:1736)
        at net.sf.saxon.Controller.transform(Controller.java:1560)
        at net.sf.saxon.s9api.XsltTransformer.transform(XsltTransformer.java:190)
        at com.occamlab.te.TECore.executeTemplate(TECore.java:517)
        at com.occamlab.te.TECore.executeTest(TECore.java:660)
        at com.occamlab.te.TECore.execute_test(TECore.java:347)
        at com.occamlab.te.TECore.execute_suite(TECore.java:390)
        at com.occamlab.te.TECore.execute(TECore.java:252)
        at com.occamlab.te.Test.main(Test.java:354)
Caused by: java.net.UnknownHostException: makc.googlecode.com
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:178)
        at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:579)
        at java.net.Socket.connect(Socket.java:528)
        at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
        at sun.net.www.http.HttpClient.<init>(HttpClient.java:211)
        at sun.net.www.http.HttpClient.New(HttpClient.java:308)
        at sun.net.www.http.HttpClient.New(HttpClient.java:326)
        at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:996)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:932)
        at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:850)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1300)
        at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:468)
        at com.sun.jersey.client.urlconnection.URLConnectionClientHandler._invoke(URLConnectionClientHandler.java:249)
        at com.sun.jersey.client.urlconnection.URLConnectionClientHandler.handle(URLConnectionClientHandler.java:149)
        ... 86 more

Jun 13, 2014 2:08:55 PM com.sun.jersey.api.client.filter.LoggingFilter log
INFO: 1 \* Client out-bound request
1 > HEAD http://www.gdal.org/gdalicon.png
1 > Accept: image/*

**Comment by bermud** [comment]
@rjmartell, I think this ca be closed?
